config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "about", to: "about#index"
  get "calculate", to: "journeys#index", as: "journeys"
  post "result", to: "journeys#result"
  get "transports", to: "transports#index"
  get "users", to: "users#index"
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journey.rb
class Journey < ApplicationRecord
  # belongs_to :users
end

app/models/transport.rb
class Transport < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  def index
    #@journeys = Journey.all
  end

  def result
    #kgCO2e
    @km = params[:km]
    @transports = Transport.all
    @i = 0
    @results = []

    @transports.each do |transport|
      @results[@i]= {
        'co2' => @km.to_f * transport.multiplier,
        'name' => transport.name
      }
      @i += 1
    end

    @journey = Journey.new
    @journey.distance = @km
    @journey.result_walk = @results[0]['co2']
    @journey.result_train = @results[1]['co2']
    @journey.result_electrical_car = @results[2]['co2']
    @journey.result_bus = @results[3]['co2']
    @journey.result_plane = @results[4]['co2']
    @journey.result_car = @results[5]['co2']
    @journey.user_id = current_user.id
    @journey.save

  end

end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  def index
    @transports = Transport.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    #@users = User.all
    # get all journeys for current user
    @journeys = Journey.where(user_id: current_user.id)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<h1>About</h1>

app/views/home/index.html.erb
<h1>
Hello
</h1>
<% if signed_in? %>
  <span><%= current_user.email %></span>
  <span>You are logged in !</span>
  <%= button_to 'Sign out', sign_out_path, method: :delete  %>  

<% else %>
  <span>Please log in...</span>
  <button><%= link_to 'register', sign_up_path %></button>
  <button><%= link_to 'Sign in', sign_in_path %></button>
<% end %>

app/views/journeys/index.html.erb
<h1>Calculte your Co2 emmision</h1>

<%# @journeys.inspect %>

<%= form_with url: "/result", method: :post do |form| %>
  <%= form.label :km, "Travel distance in km :" %>
  <%= form.number_field :km, in: 1.0..999999.0, step: 0.1 %>
  <%= form.submit "Calculer" %>
<% end %>

app/views/journeys/result.html.erb
<h1>Result</h1>
<h2>For <%= @km %> km</h2>

<%# for each result print co2 and slug %>
<% @results.each do |result| %>
  <span><%= result["name"] %> : </span>
  <span><%= result["co2"] %> kgCO2e</span>
  </br>
<% end %>

</br>
<a href="/users">See your journeys</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar">
      <ul class="navbar__container">
        <li class="navbar__element"><%= link_to 'Home', root_path, class: "navbar__link navbar__link-first" %></li>
        <%# link to about %>
        <li class="navbar__element"><%= link_to 'About', about_path, class: "navbar__link" %></li>
        <%# link to users %>
        <li class="navbar__element"><%= link_to 'My journeys', users_path, class: "navbar__link" %></li>
        <li class="navbar__element"><%= link_to 'Calculate', journeys_path, class: "navbar__link" %></li>
        <li class="navbar__element"><%= link_to 'Debug : transports', transports_path, class: "navbar__link" %></li>
      </ul>
    </nav>
    <main class="app">
      <%= yield %>
    </main>
  </body>
</html>

app/views/transports/index.html.erb
<h1>Means of transport</h1>

<%= @transports.inspect %>

app/views/users/index.html.erb
<h1>Your journeys</h1>

<%# @journeys.inspect %>

<% @journeys.each do |journey| %>
  <div class="users__container">
    <h2>For <%= journey['distance'] %> km </h2>
    <span>Walk : </span>
    <span><%= journey["result_walk"] %> kgCO2e</span>
    </br>
    <span>Train : </span>
    <span><%= journey["result_train"] %> kgCO2e</span>
    </br>
    <span>Electrical_car : </span>
    <span><%= journey["result_electrical_car"] %> kgCO2e</span>
    </br>
    <span>Bus : </span>
    <span><%= journey["result_bus"] %> kgCO2e</span>
    </br>
    <span>Car : </span>
    <span><%= journey["result_car"] %> kgCO2e</span>
    </br>
  </div>
<% end %>